name: Check article-api docs
on:
  workflow_dispatch: null
  pull_request:
    paths:
    - src/article-api/middleware/article.ts
    - src/article-api/middleware/pagelist.ts
    - .github/workflows/article-api-docs.yml
permissions:
  contents: read
jobs:
  check-content-linter-rules-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ./.github/actions/node-npm-setup
    - name: Check that src/article-api/README.md is up-to-date
      run: npm run generate-article-api-docs
    - name: Fail if it isn't up-to-date
      run: "if [ -n \"$(git status --porcelain)\" ]; then\n  git status\n  git diff\n\
        \n  # Some whitespace for the sake of the message below\n  echo \"\"\n  echo\
        \ \"\"\n\n  echo \"src/article-api/README.md is out of date.\"\n  echo \"\
        Please run 'npm run generate-article-api-docs' and commit the changes.\"\n\
        \  exit 1;\nfi\n"
