name: Auto Close Open Source Dependency Updates
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  close-external:
    if: "${{\n  github.repository == 'github/docs' &&\n  github.event.pull_request.number\
      \ &&\n  github.event.pull_request.base.ref == 'main' &&\n  github.event.pull_request.user.login\
      \ == 'dependabot[bot]' &&\n  github.event.pull_request.state == 'open'\n}}"
    runs-on: ubuntu-latest
    steps:
    - name: Close pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: 'gh pr close "$PR_URL"

        '
    - name: Comment on the pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: 'gh pr comment "$PR_URL" --body "This dependency update will be handled
        internally by our engineering team."

        '
    - name: Lock conversations
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      with:
        script: "try {\n  await github.rest.issues.lock({\n    ...context.repo,\n\
          \    issue_number: parseInt(process.env.PR_NUMBER, 10),\n    lock_reason:\
          \ 'resolved'\n  })\n  console.log('Locked the pull request to prevent spam!')\n\
          } catch (error) {\n  console.error(`Failed to lock the pull request. Error:\
          \ ${error}`)\n  throw error\n}\n"
