name: Auto-add ready-for-doc-review label
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  add-review-label:
    name: Add ready-for-doc-review label to DIY docs PRs
    if: github.repository == 'github/docs-internal' && github.event.pull_request.draft
      == false && github.actor != 'github-openapi-bot' && github.actor != 'docs-bot'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: Check team membership
      id: membership_check
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "try {\n  await github.rest.teams.getMembershipForUserInOrg({\n  \
          \  org: 'github',\n    team_slug: 'docs',\n    username: context.payload.sender.login,\n\
          \  });\n  return true\n} catch(err) {\n  console.log(err)\n  return false\n\
          }\n"
    - name: Add ready-for-doc-review label
      if: steps.membership_check.outputs.result == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: 'gh pr edit $PR_URL --add-label ready-for-doc-review

        '
