name: Changelog prompt when a PR is closed
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  comment-on-pr:
    if: github.repository == 'github/docs-internal' && github.event.pull_request.merged
      == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR author is in docs-content team
      id: check_team
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "try {\n  const pr = context.payload.pull_request;\n  await github.rest.teams.getMembershipForUserInOrg({\n\
          \    org: 'github',\n    team_slug: 'docs-content',\n    username: pr.user.login,\n\
          \  });\n  core.exportVariable('CONTINUE_WORKFLOW', 'true');\n} catch(err)\
          \ {\n  core.info(\"Workflow triggered by a merged PR, but the PR author\
          \ is not a member of the docs-content team.\");\n  core.exportVariable('CONTINUE_WORKFLOW',\
          \ 'false');\n}\n"
    - name: Post changelog instructions comment
      if: env.CONTINUE_WORKFLOW == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "// Get PR author username\nconst pr = context.payload.pull_request;\n\
          const prAuthor = pr.user.login;\n\n// Compose the comment body with readable\
          \ YAML and correct formatting\nconst commentBody =\n  \"\U0001F44B @\" +\
          \ prAuthor +\n  \" - Did this PR add noteworthy changes to the GitHub docs?\
          \ If so, you might want to publicize this by adding an entry to \" +\n \
          \ \"the [Docs changelog](https://github.com/github/docs-internal/blob/main/CHANGELOG.md).\\\
          n\\n\" +\n  \"To do this, type `/changelog` in a new comment on this PR\
          \ and complete the fields.\\n\\n\" +\n  \"A message will be posted to the\
          \ **#docs-changelog** channel and a PR will be raised to update the [CHANGELOG.md](https://github.com/github/docs-internal/blob/main/CHANGELOG.md)\
          \ file.\";\n\n// Post the comment\nawait github.rest.issues.createComment({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  issue_number:\
          \ pr.number,\n  body: commentBody\n});\n"
