name: Check for Spammy Issues
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  spammy-title-check:
    name: Remove issues with spammy titles
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "\nconst issue = context.payload.issue\nconst owner = 'github'\nconst\
          \ repo = 'docs'\n\nconst titleWordCount = issue.title.trim().split(' ').length\n\
          const titleWordCountMin = 3\n\ntry {\n  await github.rest.teams.getMembershipForUserInOrg({\n\
          \    org: 'github',\n    team_slug: 'employees',\n    username: context.payload.sender.login,\n\
          \  });\n\n  // Do not perform this workflow with GitHub employees. This\
          \ return\n  // statement only gets hit if the user is a GitHub employee\n\
          \  return\n} catch (err) {\n  // An error will be thrown if the user is\
          \ not a GitHub employee\n  // If a user is not a GitHub employee, we should\
          \ check to see if title has at least the minimum required number of words\
          \ in it and if it does, we can exit the workflow\n\n  if (titleWordCount\
          \ >= titleWordCountMin) {\n    return\n  }\n}\n\n//\n// Assuming the user\
          \ is not a GitHub employee and the issue title\n// does not contain the\
          \ minimum number of words required, proceed.\n//\n\n// Close the issue and\
          \ add the invalid label\nawait github.rest.issues.update({\n  owner: owner,\n\
          \  repo: repo,\n  issue_number: issue.number,\n  labels: ['invalid'],\n\
          \  state: 'closed'\n});\n\n// Comment on the issue\nawait github.rest.issues.createComment({\n\
          \  owner: owner,\n  repo: repo,\n  issue_number: issue.number,\n  body:\
          \ `This issue may have been opened accidentally. I'm going to close it now,\
          \ but feel free to open a new issue with a more descriptive title!`\n});\n\
          \n// Add the issue to the Done column on the triage board\ntry {\n  await\
          \ github.rest.projects.createCard({\n    column_id: 11167427,\n    content_id:\
          \ context.payload.issue.id,\n    content_type: \"Issue\"\n  });\n} catch\
          \ (error) {\n  console.log(error);\n}\n"
