name: Confirm internal staff meant to post in public
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  check-team-membership:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.repository == 'github/docs' && github.actor != 'docs-bot'
    steps:
    - id: membership_check
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        TEAM_CONTENT_REPO: ${{ secrets.TEAM_CONTENT_REPO }}
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "// Only perform this action with GitHub employees\ntry {\n  await\
          \ github.rest.teams.getMembershipForUserInOrg({\n    org: 'github',\n  \
          \  team_slug: 'employees',\n    username: context.payload.sender.login,\n\
          \  });\n} catch(err) {\n  // An error will be thrown if the user is not\
          \ a GitHub employee\n  // If a user is not a GitHub employee, we should\
          \ stop here and\n  // Not send a notification\n  return\n}\n\n// Don't perform\
          \ this action with Docs team members\ntry {\n  await github.rest.teams.getMembershipForUserInOrg({\n\
          \    org: 'github',\n    team_slug: 'docs',\n    username: context.payload.sender.login,\n\
          \  });\n  // If the user is a Docs team member, we should stop here and\
          \ not send\n  // a notification\n  return\n} catch(err) {\n  // An error\
          \ will be thrown if the user is not a Docs team member\n  // If a user is\
          \ not a Docs team member we should continue and send\n  // the notification\n\
          }\n\nconst issueNo = context.number || context.issue.number\n\n// Create\
          \ an issue in our private repo\nawait github.rest.issues.create({\n  owner:\
          \ 'github',\n  repo: process.env.TEAM_CONTENT_REPO,\n  title: `@${context.payload.sender.login}\
          \ confirm that \\#${issueNo} should be in the public github/docs repo`,\n\
          \  body: `@${context.payload.sender.login} opened https://github.com/github/docs/issues/${issueNo}\
          \ publicly in the github/docs repo, instead of the private github/${process.env.TEAM_CONTENT_REPO}\
          \ repo.\\n\\n@${context.payload.sender.login}, please confirm that this\
          \ belongs in the public repo and that no sensitive information was disclosed\
          \ by commenting below and closing the issue.\\n\\nIf this was not intentional\
          \ and sensitive information was shared, please delete https://github.com/github/docs/issues/${issueNo}\
          \ and notify us in the \\#docs-open-source channel.\\n\\nThanks!`,\n  labels:\
          \ ['OS confirmation', 'skip FR board'],\n});\n\ncore.setOutput('did_warn',\
          \ 'true')\n"
    - name: Send Slack notification if a GitHub employee who isn't on the docs team
        opens an issue in public
      if: ${{ steps.membership_check.outputs.did_warn && github.repository == 'github/docs'
        }}
      uses: someimportantcompany/github-actions-slack-message@a975b440de2bcef178d451cc70d4c1161b5a30cd
      with:
        channel: ${{ secrets.DOCS_OPEN_SOURCE_SLACK_CHANNEL_ID }}
        bot-token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
        text: <@${{github.actor}}> opened https://github.com/github/docs/issues/${{
          github.event.number || github.event.issue.number }} publicly on the github/docs
          repo instead of a private repo. They have been notified via a new issue
          in the private repo to confirm this was intentional.
    - name: Check out repo
      if: ${{ failure() && github.event_name != 'pull_request_target' }}
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name != 'pull_request_target' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
