name: Check content-linter rules docs
on:
  workflow_dispatch: null
  pull_request:
    paths:
    - src/content-linter/**
    - package-lock.json
    - data/reusables/contributing/content-linter-rules.md
    - .github/workflows/content-linter-rules-docs.yml
permissions:
  contents: read
jobs:
  check-content-linter-rules-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: ./.github/actions/node-npm-setup
    - name: Check that content-linter-rules.md is up-to-date
      run: npm run generate-content-linter-docs
    - name: Fail if it isn't up-to-date
      run: "if [ -n \"$(git status --porcelain)\" ]; then\n  git status\n  git diff\n\
        \n  # Some whitespace for the sake of the message below\n  echo \"\"\n  echo\
        \ \"\"\n\n  echo \"content-linter-rules.md is out of date.\"\n  echo \"Please\
        \ run 'npm run generate-content-linter-docs' and commit the changes.\"\n \
        \ exit 1;\nfi\n"
