name: Count translation corruptions
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  count-translation-corruptions:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout English repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - name: Clone all translations
      uses: ./.github/actions/clone-translations
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - uses: ./.github/actions/node-npm-setup
    - name: Run count
      run: npm run count-translation-corruptions
