name: Create a PR to add an entry to the CHANGELOG.md file in this repo
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
env:
  CHANGELOG_FILE: CHANGELOG.md
  CHANGELOG_FILE_URL: https://github.com/github/docs-internal/blob/main/CHANGELOG.md
jobs:
  docs-changelog-pr:
    if: ${{ github.repository == 'github/docs-internal' && github.event.issue.pull_request
      }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.1
    - name: Ensure ${{ env.CHANGELOG_FILE }} exists
      run: "if [ ! -f ${{ env.CHANGELOG_FILE }} ]; then\n  echo \"${{ env.CHANGELOG_FILE\
        \ }} is missing at the root of the repository.\"\n  exit 1\nfi\n"
    - name: Check that the user belongs to the github org
      id: hubber_check
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "try {\n  await github.rest.teams.getMembershipForUserInOrg({\n  \
          \  org: 'github',\n    team_slug: 'employees',\n    username: context.payload.sender.login,\n\
          \  });\n  core.exportVariable('CONTINUE_WORKFLOW', 'true');\n} catch(err)\
          \ {\n  core.info(\"Workflow triggered by a comment, but the commenter is\
          \ not a Hubber. Exiting.\");\n  core.exportVariable('CONTINUE_WORKFLOW',\
          \ 'false');\n}\n"
    - name: Check if comment starts with '## Changelog summary'
      if: env.CONTINUE_WORKFLOW == 'true'
      id: check_summary
      env:
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: "# Get the first line of the comment and trim the leading/trailing whitespace:\n\
        FIRST_LINE=$(printf \"%s\\n\" \"$COMMENT_BODY\" | head -n1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')\n\
        if [[ \"$FIRST_LINE\" != '## Changelog summary' ]]; then\n  echo \"FIRST_LINE=|$FIRST_LINE|\"\
        \n  echo \"The pull request comment is not a changelog summary. Exiting.\"\
        \n  echo \"CONTINUE_WORKFLOW=false\" >> $GITHUB_ENV\nfi\n"
    - name: Create changelog text
      if: env.CONTINUE_WORKFLOW == 'true'
      id: create_text
      env:
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: "set -euo pipefail\nDATE=$(date +\"**%-d %B %Y**\")\nBODY=\"$(printf \"\
        %s\\n\" \"$COMMENT_BODY\" | tail -n +2)\"\nCHANGELOG_TEXT=\"$(printf \"%s\\\
        n\" \"$BODY\" | awk '/^:writing_hand:/{exit} {print}')\"\n{\n  echo \"$DATE\"\
        \n  echo -e \"$CHANGELOG_TEXT\\n<hr>\"\n} > changelog_entry.txt\n"
    - name: Set up git
      if: env.CONTINUE_WORKFLOW == 'true'
      run: 'git config user.name "github-actions[bot]"

        git config user.email "github-actions[bot]@users.noreply.github.com"

        '
    - name: Prepare branch
      if: env.CONTINUE_WORKFLOW == 'true'
      run: 'BRANCH="changelog-update-$(date +%s)"

        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

        git checkout -b "$BRANCH"


        # Insert new changelog entry after the first heading, as follows:

        # Print the first line of the existing CHANGELOG.md file into a `tmp` file,
        followed by an empty line.

        # Then, print the contents of `changelog_entry.txt` into the `tmp` file.

        # Then, print the rest of the existing CHANGELOG.md file into the `tmp` file.

        # Finally, replace the existing CHANGELOG.md file with the `tmp` file.

        awk ''NR==1{print; print ""; while ((getline line < "changelog_entry.txt")
        > 0) print line; next}1'' CHANGELOG.md > tmp && mv tmp CHANGELOG.md


        git add CHANGELOG.md

        git commit -m "Update changelog for $(head -n1 changelog_entry.txt)"

        git push origin "$BRANCH"

        '
    - name: Create a pull request
      if: env.CONTINUE_WORKFLOW == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      id: create_pull_request
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "const { data: pullRequest } = await github.rest.pulls.create({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  title: `Update\
          \ docs changelog (for PR #${context.payload.issue.number})`,\n  body: `###\
          \ Automated docs changelog update\\n\\n**Purpose:** Update the <code>[${{\
          \ env.CHANGELOG_FILE }}](${{ env.CHANGELOG_FILE_URL }})</code> file with\
          \ details of a recent docs change.\\n\\nThis PR is an automated update,\
          \ generated by the <code>create-changelog-pr.yml</code> Actions workflow\
          \ as a result of a \"Changelog summary\" comment being added to [PR #${context.payload.issue.number}](${context.payload.issue.html_url}).\\\
          n\\n**Notes for reviewer**:\\n- This change to the <code>[${{ env.CHANGELOG_FILE\
          \ }}](${{ env.CHANGELOG_FILE_URL }})</code> file will be synced to the public\
          \ docs site, so make sure that the content of the entry is appropriate for\
          \ public consumption. If the content is wholly inappropriate for public\
          \ consumption, then this PR can be closed.\\n- Make sure the format of this\
          \ changelog entry is consistent with the other entries in the file.\\n\\\
          n<details><summary>Original PR comment posted by @${context.payload.comment.user.login},\
          \ using the <code>/changelog</code> slash command:</summary>\\n\\n${context.payload.comment.body}</details>`,\n\
          \  head: process.env.BRANCH,\n  base: 'main'\n});\n\ncore.setOutput('pull-request-number',\
          \ pullRequest.number);\ncore.setOutput('pull-request-url', pullRequest.html_url);\n"
    - name: Add 'ready-for-doc-review' and 'skip FR board' labels to PR
      if: env.CONTINUE_WORKFLOW == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        PULL_REQUEST_NUMBER: ${{ steps.create_pull_request.outputs.pull-request-number
          }}
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "await github.rest.issues.addLabels({\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n  issue_number: Number(process.env.PULL_REQUEST_NUMBER),\n\
          \  labels: ['ready-for-doc-review','skip FR board']\n});\n"
    - name: Assign PR to commenter
      if: env.CONTINUE_WORKFLOW == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        PULL_REQUEST_NUMBER: ${{ steps.create_pull_request.outputs.pull-request-number
          }}
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "try {\n  const username = context.payload.comment.user.login;\n \
          \ await github.rest.issues.addAssignees({\n    owner: context.repo.owner,\n\
          \    repo: context.repo.repo,\n    issue_number: Number(process.env.PULL_REQUEST_NUMBER),\n\
          \    assignees: [username]\n  });\n} catch (err) {\n  core.info(`Failed\
          \ to assign PR to @${context.payload.comment.user.login}: ${err.message}`);\n\
          }\n"
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
