name: Feedback prompt for non-Docs team contributors when a PR is closed
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  comment-on-pr:
    if: github.repository == 'github/docs-internal' && github.event.pull_request.merged
      == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR author is in docs-content team
      id: check_team
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "try {\n  const pr = context.payload.pull_request;\n  await github.rest.teams.getMembershipForUserInOrg({\n\
          \    org: 'github',\n    team_slug: 'docs-content',\n    username: pr.user.login,\n\
          \  });\n  // Author is in the team. Do nothing!\n} catch(err) {\n  // Author\
          \ not in team\n  core.exportVariable('NON_DOCS_HUBBER', 'true');\n}\n"
    - name: Post changelog instructions comment
      if: env.NON_DOCS_HUBBER == 'true'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "const pr = context.payload.pull_request;\nconst prAuthor = pr.user.login;\n\
          const assignees = (pr.assignees ?? [])\n  .filter(a => a.login.toLowerCase()\
          \ !== \"copilot\")\n  .map(a => \"@\" + a.login)\n  .join(\" \");\n\nlet\
          \ commentBody;\n\nif (assignees) {\n  commentBody =\n    \"\U0001F44B \"\
          \ + assignees +\n    \" - Please leave us feedback on your contributing\
          \ experience! \" +\n    \"To do this, please go to `#docs-contributor-feedback`\
          \ on Slack.\";\n} else if (prAuthor.toLowerCase() !== \"copilot\") {\n \
          \ commentBody =\n    \"\U0001F44B @\" + prAuthor +\n    \" - Please leave\
          \ us feedback on your contributing experience! \" +\n    \"To do this, please\
          \ go to `#docs-contributor-feedback` on Slack.\";\n} else {\n  // nobody\
          \ to mention!\n  commentBody =\n    \"\U0001F44B Please leave us feedback\
          \ on your contributing experience! \" +\n    \"To do this, please go to\
          \ `#docs-contributor-feedback` on Slack.\";\n}\n\nawait github.rest.issues.createComment({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  issue_number:\
          \ pr.number,\n  body: commentBody\n});\n"
