name: Generate code scanning query lists
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  generate-security-query-lists:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Checkout codeql repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        repository: github/codeql
        path: codeql
        ref: ${{ inputs.SOURCE_BRANCH || 'main' }}
    - name: Get the codeql SHA being synced
      id: codeql
      shell: bash
      run: 'cd codeql

        OPENAPI_COMMIT_SHA=$(git rev-parse HEAD)

        echo "OPENAPI_COMMIT_SHA=$OPENAPI_COMMIT_SHA" >> $GITHUB_OUTPUT

        echo "Copied files from github/codeql repo. Commit SHA: $OPENAPI_COMMIT_SHA"

        '
    - name: Download CodeQL CLI
      uses: ./codeql/.github/actions/fetch-codeql
    - name: Test CodeQL CLI Download
      shell: bash
      run: codeql --version
    - name: Start CodeQL CLI server in the background
      shell: bash
      run: 'codeql execute cli-server &

        sleep 3

        codeql --version

        '
    - uses: ./.github/actions/install-cocofix
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - name: Build code scanning security query lists
      shell: bash
      run: "for lang in \"actions\" \"cpp\" \"csharp\" \"go\" \"java\" \"javascript\"\
        \ \"python\" \"ruby\" \"rust\" \"swift\"; do\n  echo \"Generating code scanning\
        \ query list for $lang\"\n  npm run generate-code-scanning-query-list -- \\\
        \n    --verbose \\\n    --codeql-path codeql \\\n    --codeql-dir codeql \\\
        \n    -o data/reusables/code-scanning/codeql-query-tables/$lang.md \\\n  \
        \  $lang\ndone\n"
    - name: Upload security query lists
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: security-query-lists
        path: data/reusables/code-scanning/codeql-query-tables/
  generate-quality-query-lists:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Checkout codeql repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        repository: github/codeql
        path: codeql
        ref: ${{ inputs.SOURCE_BRANCH || 'main' }}
    - name: Get the codeql SHA being synced
      id: codeql
      shell: bash
      run: 'cd codeql

        OPENAPI_COMMIT_SHA=$(git rev-parse HEAD)

        echo "OPENAPI_COMMIT_SHA=$OPENAPI_COMMIT_SHA" >> $GITHUB_OUTPUT

        echo "Copied files from github/codeql repo. Commit SHA: $OPENAPI_COMMIT_SHA"

        '
    - name: Download CodeQL CLI
      uses: ./codeql/.github/actions/fetch-codeql
    - name: Test CodeQL CLI Download
      shell: bash
      run: codeql --version
    - name: Start CodeQL CLI server in the background
      shell: bash
      run: 'codeql execute cli-server &

        sleep 3

        codeql --version

        '
    - name: Build code quality query lists
      shell: bash
      run: "for lang in \"csharp\" \"go\" \"java\" \"javascript\" \"python\" \"ruby\"\
        ; do\n  echo \"Generating code quality query list for $lang\"\n  npm run generate-code-quality-query-list\
        \ -- \\\n    --verbose \\\n    --codeql-path codeql \\\n    --codeql-dir codeql\
        \ \\\n    -o data/reusables/code-quality/codeql-query-tables/$lang.md \\\n\
        \    $lang\ndone\n"
    - name: Upload quality query lists
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: quality-query-lists
        path: data/reusables/code-quality/codeql-query-tables/
  create-pull-request:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    needs:
    - generate-security-query-lists
    - generate-quality-query-lists
    steps:
    - name: Checkout repository code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: Checkout codeql repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        repository: github/codeql
        path: codeql
        ref: ${{ inputs.SOURCE_BRANCH || 'main' }}
    - name: Get the codeql SHA being synced
      id: codeql
      shell: bash
      run: 'cd codeql

        OPENAPI_COMMIT_SHA=$(git rev-parse HEAD)

        echo "OPENAPI_COMMIT_SHA=$OPENAPI_COMMIT_SHA" >> $GITHUB_OUTPUT

        echo "Copied files from github/codeql repo. Commit SHA: $OPENAPI_COMMIT_SHA"

        '
    - name: Download security query lists
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
      with:
        name: security-query-lists
        path: data/reusables/code-scanning/codeql-query-tables/
    - name: Download quality query lists
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
      with:
        name: quality-query-lists
        path: data/reusables/code-quality/codeql-query-tables/
    - name: Insight into diff
      shell: bash
      run: 'git diff

        '
    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        DRY_RUN: ${{ github.event_name == 'pull_request'}}
      shell: bash
      run: "\n# When we started, we downloaded the CodeQL CLI here in this workflow.\n\
        # We have no intention of checking that in but we also don't want\n# `git\
        \ status ...` to show it as an untracked file.\nrm -fr ./codeql\n\n# If nothing\
        \ to commit, exit now. It's fine. No orphans.\nchanges=$(git diff --name-only\
        \ | wc -l)\nuntracked=$(git status --untracked-files --short | wc -l)\nif\
        \ [[ $changes -eq 0 ]] && [[ $untracked -eq 0 ]]; then\n  echo \"There are\
        \ no changes to commit after running the generation and conversion scripts.\
        \ Exiting...\"\n  exit 0\nfi\n\ngit config --global user.name \"docs-bot\"\
        \ngit config --global user.email \"77750099+docs-bot@users.noreply.github.com\"\
        \n\nbranchname=codeql-query-tables-${{ steps.codeql.outputs.OPENAPI_COMMIT_SHA\
        \ }}\n\n# Exit if the branch already exists. Since the actions/checkout fetch-depth\
        \ is 1,\n# it doesn't \"know\" about branches locally, so we need to manually\
        \ list them.\nbranchExists=$(git ls-remote --heads origin refs/heads/$branchname\
        \ | wc -l)\n\n# When run on a pull_request, we're just testing the tooling.\n\
        # Exit before it actually pushes the possible changes.\nif [ \"$DRY_RUN\"\
        \ = \"true\" ]; then\n  echo \"Dry-run mode when run in a pull request\"\n\
        \  echo \"See the 'Insight into diff' step for the changes it would create\
        \ PR about.\"\n  exit 0\nfi\n\nif [ $branchExists -ne 0 ]; then\n  echo \"\
        Branch $branchname already exists in the remote repository.\"\n  exit 0\n\
        else\n  git checkout -b $branchname\nfi\n\ngit add data/reusables/code-scanning/codeql-query-tables\n\
        git add data/reusables/code-quality/codeql-query-tables\ngit commit -m \"\
        Update CodeQL query tables\"\ngit push -u origin $branchname\n\necho \"Creating\
        \ pull request...\"\ngh pr create \\\n  --title \"Update CodeQL query tables\"\
        \ \\\n  --repo github/docs-internal \\\n --label \"codeql-query-tables,skip\
        \ FR board,ready-for-doc-review,workflow-generated\" \\\n  --body '\U0001F44B\
        \ humans. This PR updates the **CodeQL query table reusables** with the latest\
        \ changes in preparation for the next **CodeQL CLI** release. (Synced from\
        \ codeql@${{ steps.codeql.outputs.OPENAPI_COMMIT_SHA }})\n\n\n  No action\
        \ is required from the first responder for the Docs content team. This PR\
        \ is automatically added to the Docs content review board. Any writer can\
        \ review this by checking that the PR looks sensible. If CI does not pass\
        \ or other problems arise, contact #docs-engineering on slack.\n\n\n  When\
        \ the DRI for the CodeQL CLI release is ready to publish, they will ask us\
        \ to merge this PR in #docs-content.'\n"
