name: Headless Tests
on:
  workflow_dispatch: null
  merge_group: null
  pull_request: null
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
  cancel-in-progress: true
env:
  ELASTICSEARCH_URL: http://localhost:9200/
jobs:
  playwright-tests:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
        - playwright-rendering
        - playwright-a11y
      fail-fast: false
    timeout-minutes: 60
    steps:
    - name: Check out repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ./.github/actions/setup-elasticsearch
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/cache-nextjs
    - name: Run build script
      run: npm run build
    - name: Index fixtures into the local Elasticsearch
      run: npm run index-test-fixtures
    - name: Install headless browser
      run: npx playwright install --no-shell
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_WORKERS: ${{ fromJSON('[1, 4]')[github.repository == 'github/docs-internal']
          }}
      run: npm run playwright-test -- ${{ matrix.node }} --reporter list
