name: Hubber contribution help
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  check-team-membership:
    if: github.repository == 'github/docs-internal' && github.actor != 'github-openapi-bot'
      && github.actor != 'docs-bot'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - id: membership_check
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
        script: "try {\n  await github.rest.teams.getMembershipForUserInOrg({\n  \
          \  org: 'github',\n    team_slug: 'docs',\n    username: context.payload.sender.login,\n\
          \  });\n  return true\n} catch(err) {\n  return false\n}\n"
    - name: Comment on the PR
      if: steps.membership_check.outputs.result == 'false'
      run: "gh pr comment $PR --body \"## Requesting a review from the Docs team\n\
        \n### \U0001F6A7 Draft PRs\n\nTo add the PR to the Docs Content review board,\
        \ click **Ready for review** in the merge box.\n\n### \U0001F680 Non-draft\
        \ PRs\n\nThe PR is **ready** and has automatically been added to the Docs\
        \ Content review board. The docs team will review it as soon as possible.\n\
        \n### Lead time for review\n\nPlease allow at least 3 business days for a\
        \ Docs Content review.\n\n### Need help?\n\nReach out in [#docs-content](https://github-grid.enterprise.slack.com/archives/C0E9DK082)\
        \ on Slack.\"\n"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.html_url }}
