name: 'Link Checker: On PR'
on:
  workflow_dispatch: null
  merge_group: null
  pull_request: null
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
  cancel-in-progress: true
jobs:
  check-links:
    runs-on: ubuntu-latest
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/get-docs-early-access
      if: ${{ github.repository == 'github/docs-internal' }}
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - name: Link check all pages (internal links only)
      env:
        LEVEL: critical
        ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{
          github.run_id }}
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        SHOULD_COMMENT: ${{ secrets.DOCS_BOT_PAT_BASE != '' }}
        CHECK_EXTERNAL_LINKS: false
        CREATE_REPORT: false
        CHECK_ANCHORS: true
        ENABLED_LANGUAGES: en
        FAIL_ON_FLAW: true
      run: npm run rendered-content-link-checker
