name: Local development
on:
  merge_group: null
  pull_request: null
permissions:
  contents: read
jobs:
  local-dev:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/get-docs-early-access
      if: ${{ github.repository == 'github/docs-internal' }}
      with:
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
    - name: Disable Next.js telemetry
      run: npx next telemetry disable
    - name: Install headless browser
      run: npx playwright install --no-shell
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_START_SERVER_COMMAND: npm start
        PLAYWRIGHT_RETRIES: 0
        TEST_EARLY_ACCESS: ${{ github.repository == 'github/docs-internal' }}
      run: npm run playwright-test -- playwright-local-dev
    - name: Start server in the background
      run: npm start > /tmp/stdout.log 2> /tmp/stderr.log &
    - name: View the home page
      run: 'echo "Going to sleep a little to wait for the server to start"

        sleep 10

        curl --fail --retry-connrefused --retry 5 http://localhost:4000/

        '
    - name: Run basic tests
      run: npm run test-local-dev
    - if: ${{ failure() }}
      name: Debug server outputs on errors
      run: 'echo "____STDOUT____"

        cat /tmp/stdout.log

        echo "____STDERR____"

        cat /tmp/stderr.log

        '
    - name: Pre-commit hooks should prevent bad Markdown edits
      run: "set -e\n\n# This test assumes this one file always exists\nls content/get-started/start-your-journey/hello-world.md\n\
        \n# Not sure if it matters but we're in a detached HEAD state\n# after the\
        \ actions/checkout action.\ngit checkout -b my-new-branch\n# Also, do this\
        \ so you don't get errors from git about this\n# not being set up before your\
        \ first commit attempt\ngit config user.name github-actions\ngit config user.email\
        \ github-actions@github.com\n\n# To know what will fail the markdown lint,\
        \ see src/content-linter/style/github-docs.js\n# Add some NOT valid Markdown\
        \ to it\n# In this case an internal link with a hardcode /en/ prefix.\necho\
        \ \"This *is** not valid [Markdown](/en/foo)\" >> content/get-started/start-your-journey/hello-world.md\n\
        git commit -a -m \"this should fail\"\nexit_code=$?\nif [ $exit_code != 0\
        \ ]; then\n  echo \"That SHOULD have failed, but it DIDN'T\"\n  exit 1\nelse\n\
        \  echo \"As expected, it failed :)\"\nfi\n"
