name: Update Moda allowed IPs
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  update-moda-allowed-ips:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v6.0.1
    - name: Update list of allowed IPs
      run: "echo \"Getting a list of Fastly IP addresses....\"\nips=$( \\\n  curl\
        \ -s https://api.fastly.com/public-ip-list \\\n  | jq -r '.addresses | join(\"\
        ,\")' \\\n)\necho \"Got a list of Fastly IP addresses: $ips\"\n\necho \"Updating\
        \ the list of allowed IPs in Moda config...\"\nyq -i \".metadata.annotations[\\\
        \"moda.github.net/allowed-ips\\\"] = \\\"$ips\\\"\" \\\n  config/kubernetes/production/services/webapp.yaml\n\
        echo \"Updated the list of allowed IPs in Moda config\"\n\necho \"Checking\
        \ if there is a change to make...\"\nif git diff --quiet; then\n  echo \"\
        No changes to the allowed IPs\"\n  exit 0\nfi\n\necho \"Change found; making\
        \ a pull request...\"\nbranchname=update-allowed-ips-$(date +%s)\ngit checkout\
        \ -b $branchname\ngit commit -am \"Update list of allowed IPs\"\ngit push\n\
        gh pr create \\\n  --title \"Update list of allowed IPs\" \\\n  --body 'This\
        \ PR updates the list of allowed IPs in Moda. It is automatically generated.'\
        \ \\\n  --label \"workflow-generated\" \\\n  --head=$branchname\necho \"Pull\
        \ request created\"\n"
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
