name: Move content script test
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  move-content-test:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Set up a dummy git user
      run: '# These must be set to something before running the move-content

        # script because it depends on executing `git mv ...`

        # and `git commit ...`

        git config --global user.name "docs-bot"

        git config --global user.email "77750099+docs-bot@users.noreply.github.com"

        '
    - name: Move hello-world.md to hello-wurld.md
      env:
        ROOT: src/fixtures/fixtures
      run: "npm run move-content -- \\\n  src/fixtures/fixtures/content/get-started/start-your-journey/hello-world.md\
        \ \\\n  src/fixtures/fixtures/content/get-started/start-your-journey/hello-wurld.md\n\
        \nnpm run test-moved-content -- \\\n  src/fixtures/fixtures/content/get-started/start-your-journey/hello-world.md\
        \ \\\n  src/fixtures/fixtures/content/get-started/start-your-journey/hello-wurld.md\n\
        \n# TODO: Add tests that inspects the git log\ngit log | head -n 100\n"
    - name: Move code-security/getting-started to code-security/got-started
      env:
        ROOT: src/fixtures/fixtures
      run: "npm run move-content -- \\\n  src/fixtures/fixtures/content/code-security/getting-started\
        \ \\\n  src/fixtures/fixtures/content/code-security/got-started\n\nnpm run\
        \ test-moved-content -- \\\n  src/fixtures/fixtures/content/code-security/getting-started\
        \ \\\n  src/fixtures/fixtures/content/code-security/got-started\n\n# TODO:\
        \ Add tests that inspects the git log\ngit log | head -n 100\n"
