name: Move and unlabel ready to merge PRs
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  unmark_for_review:
    if: "${{\n  github.repository == 'github/docs' &&\n  github.event.label.name ==\
      \ 'ready to merge'\n}}"
    runs-on: ubuntu-latest
    steps:
    - name: move PR
      uses: alex-page/github-project-automation-plus@303f24a24c67ce7adf565a07e96720faf126fe36
      with:
        project: Docs open source board
        column: Triage
        repo-token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: remove label
      uses: ./.github/actions/labeler
      with:
        ignoreifAssigned: false
        removeLabels: waiting for review
