name: Move Reopened Issues to Triage
on:
  workflow_dispatch: {}
permissions:
  contents: read
  repository-projects: write
jobs:
  move-reopened-issue-to-triage:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        script: "const issueNumber = context.issue.number;\nconst doneColumnId = 11167427;\n\
          const triageColumnId = 11007039;\n\ntry {\n  const cards = await github.rest.projects.listCards({\n\
          \    column_id: doneColumnId\n  });\n\n  for (const card of cards) {\n \
          \   if (card.content_url.endsWith(`/${issueNumber}`)) {\n      await github.rest.projects.moveCard({\n\
          \        card_id: card.id,\n        position: 'position',\n        column_id:\
          \ triageColumnId\n      });\n    }\n  }\n} catch(e) {\n  console.log(e);\n\
          }\n"
    - name: Check out repo
      if: ${{ failure() }}
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
