name: Notify When Maintainers Cannot Edit
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  notify-when-maintainers-cannot-edit:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        script: "const query = `\n  query($number: Int!) {\n    repository(owner:\
          \ \"github\", name: \"docs\") {\n      pullRequest(number: $number) {\n\
          \        headRepositoryOwner {\n          login\n        }\n        maintainerCanModify\n\
          \      }\n    }\n  }\n`;\n\nconst pullNumber = context.issue.number;\nconst\
          \ variables = { number: pullNumber };\n\ntry {\n  console.log(`Check github/docs#${pullNumber}\
          \ for maintainer edit access ...`);\n  const result = await github.graphql(query,\
          \ variables);\n\n  console.log(JSON.stringify(result, null, 2));\n\n  const\
          \ pullRequest = result.repository.pullRequest;\n\n  if (pullRequest.headRepositoryOwner.login\
          \ === 'github') {\n    console.log('PR owned by github');\n    return;\n\
          \  }\n\n  if (!pullRequest.maintainerCanModify) {\n    console.log('PR not\
          \ owned by github and does not have maintainer edits enabled');\n\n    await\
          \ github.rest.issues.createComment({\n      issue_number: pullNumber,\n\
          \      owner: 'github',\n      repo: 'docs',\n      body: \"Thanks for submitting\
          \ a PR to the GitHub Docs project!\\n\\nIn order to review and merge PRs\
          \ most efficiently, we require that all PRs grant maintainer edit access\
          \ before we review them. For information on how to do this, [see the documentation](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).\"\
          \n    });\n  }\n} catch(e) {\n  console.log(e);\n}\n"
