name: Notify about production deployment
on:
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: write
jobs:
  find-pr-and-post-comment:
    if: "${{\n  github.repository == 'github/docs-internal' &&\n  (github.event_name\
      \ != 'workflow_run' ||\n  github.event.workflow_run.conclusion == 'success')\n\
      }}"
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Sleep a little to give Fastly Purge a chance
      run: sleep 30
    - name: Find last PR
      id: get-number
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
      run: npm run find-past-built-pr
    - name: Find content directory changes comment
      if: ${{ steps.get-number.outputs.number != '' }}
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
      id: findComment
      with:
        issue-number: ${{ steps.get-number.outputs.number }}
        comment-author: github-actions[bot]
        body-includes: <!-- GONE_TO_PRODUCTION -->
    - name: Update comment
      if: ${{ steps.get-number.outputs.number != '' }}
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
      with:
        comment-id: ${{ steps.findComment.outputs.comment-id }}
        issue-number: ${{ steps.get-number.outputs.number }}
        body: "<!-- GONE_TO_PRODUCTION -->\n\U0001F680 **This pull request has gone\
          \ into production!**\n\nThe SHA of https://docs.github.com/_build matches\
          \ the merge commit in this PR.\n\nIf you don't see updates when expected,\
          \ try adding a random query string to the URL like `?bla=1234` and see if\
          \ that helps.\nIf that shows the expected content, it would indicate that\
          \ the CDN is \"overly caching\" the page still. It will eventually update,\
          \ but it can take a while.\n"
        edit-mode: replace
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
