name: Orphaned features check
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  orphaned-features-check:
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout English repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - name: Clone all translations
      uses: ./.github/actions/clone-translations
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - uses: ./.github/actions/node-npm-setup
    - name: Check for orphaned features
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        DRY_RUN: ${{ github.event_name == 'pull_request'}}
      run: "set -e\n\nnpm run find-orphaned-features -- find --verbose --output /tmp/orphaned-features.json\n\
        \nif [ -f /tmp/orphaned-features.json ]; then\n  echo \"Orphaned features\
        \ found:\"\n  cat /tmp/orphaned-features.json\nelse\n  echo \"No orphaned\
        \ features found\"\n  exit 0\nfi\n\nnpm run find-orphaned-features -- delete\
        \ --verbose /tmp/orphaned-features.json\n\ngit status\n\n# When run on a pull_request,\
        \ we're just testing the tooling.\n# Exit before it actually pushes the possible\
        \ changes.\nif [ \"$DRY_RUN\" = \"true\" ]; then\n  echo \"Dry-run mode when\
        \ run in a pull request\"\n  exit 0\nfi\n\n# Replicated from the translation\
        \ pipeline PR-maker Action\ngit config --global user.name \"docs-bot\"\ngit\
        \ config --global user.email \"77750099+docs-bot@users.noreply.github.com\"\
        \n\ndate=$(date '+%Y-%m-%d-%H-%M')\nbranchname=orphaned-features-$date-$GITHUB_RUN_ID\n\
        \ngit checkout -b $branchname\ngit commit -a -m \"Delete orphaned features\
        \ $date\"\ngit push origin $branchname\n\nbody=$(cat <<-EOM\n  Found with\
        \ the 'npm run find-orphaned-features' script.\n  The orphaned features workflow\
        \ file .github/workflows/orphaned-features-check.yml\n  runs every Monday\
        \ at 16:20 UTC / 8:20 PST.\n  The first responder should just spot-check some\
        \ of the orphans\n  to make sure they aren't referenced anywhere\n  and then\
        \ approve and merge the pull request.\n  For more information, see [Doc: Orphaned\
        \ Features](https://github.com/github/docs-engineering/blob/main/docs/orphaned-features.md).\n\
        EOM\n)\n\ngh pr create \\\n  --title \"Delete orphaned features ($date)\"\
        \ \\\n  --body \"$body\" \\\n  --repo github/docs-internal \\\n  --label docs-content-fr,workflow-generated\n"
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name == 'schedule' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
