name: Orphaned files check
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  orphaned-files-check:
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout English repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - name: Clone all translations
      uses: ./.github/actions/clone-translations
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - uses: ./.github/actions/node-npm-setup
    - name: Check for orphaned assets and reusables
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        DRY_RUN: ${{ github.event_name == 'pull_request'}}
      run: "set -e\n\n# The `-s` is to make npm run silent and not print verbose\n\
        # information about the npm script alias.\nassetFilesToRemove=$(npm run -s\
        \ find-orphaned-assets)\nreusableFilesToRemove=$(npm run -s reusables -- find\
        \ unused | grep '^data/reusables' || true)\n[ -z \"$assetFilesToRemove\" ]\
        \ && [ -z \"$reusableFilesToRemove\" ] && exit 0\n\nif [ -n \"$assetFilesToRemove\"\
        \ ]; then\n  echo $assetFilesToRemove | xargs git rm\nfi\nif [ -n \"$reusableFilesToRemove\"\
        \ ]; then\n  echo $reusableFilesToRemove | xargs git rm\nfi\n\ngit status\n\
        \n# If nothing to commit, exit now. It's fine. No orphans.\ngit status --\
        \ ':!translations*' | grep 'nothing to commit' && exit 0\n\n# When run on\
        \ a pull_request, we're just testing the tooling.\n# Exit before it actually\
        \ pushes the possible changes.\nif [ \"$DRY_RUN\" = \"true\" ]; then\n  echo\
        \ \"Dry-run mode when run in a pull request\"\n  exit 0\nfi\n\n# Replicated\
        \ from the translation pipeline PR-maker Action\ngit config --global user.name\
        \ \"docs-bot\"\ngit config --global user.email \"77750099+docs-bot@users.noreply.github.com\"\
        \n\ndate=$(date '+%Y-%m-%d-%H-%M')\nbranchname=orphaned-files-$date-$GITHUB_RUN_ID\n\
        \ngit checkout -b $branchname\ngit commit -m \"Delete orphaned files $date\"\
        \ngit push origin $branchname\n\nbody=$(cat <<-EOM\n  Found with the `npm\
        \ run find-orphaned-assets` and `npm run -s reusables -- find unused` scripts.\n\
        \n  The orphaned files workflow file .github/workflows/orphaned-files-check.yml\
        \ runs every Monday at 16:20 UTC / 8:20 PST.\n\n  If you are the first responder,\
        \ please spot check some of the unused assets to make sure they aren't referenced\
        \ anywhere. Then, approve and merge the pull request.\n\n  For more information,\
        \ see [Doc: Orphaned Assets](https://github.com/github/docs-engineering/blob/main/docs/orphaned-assets.md)\
        \ and [Doc: Reusables CLI](https://github.com/github/docs-internal/tree/main/src/content-render/scripts/reusables-cli).\n\
        EOM\n)\n\ngh pr create \\\n  --title \"Delete orphaned files ($date)\" \\\n\
        \  --body \"$body\" \\\n  --repo github/docs-internal \\\n  --label docs-content-fr,workflow-generated\n"
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name == 'schedule' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
