name: Purge Fastly
on:
  workflow_dispatch: {}
permissions:
  contents: read
env:
  FASTLY_TOKEN: ${{ secrets.FASTLY_TOKEN }}
  FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
jobs:
  send-purges:
    if: "${{\n  github.repository == 'github/docs-internal' &&\n  (github.event_name\
      \ != 'deployment_status' ||\n   github.event.deployment_status.state == 'success'\
      \ && github.event.deployment_status.environment == 'production')\n}}"
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Wait for production to match build number
      run: "needs=$(git rev-parse HEAD)\nstart_time=$(date +%s)\ntimeout_seconds=1200\n\
        while [[ $needs != $(curl -s --fail --retry-connrefused --retry 5 https://docs.github.com/_build)\
        \ ]]\ndo\n  if [[ $(($(date +%s) - $start_time)) -gt $timeout_seconds ]]\n\
        \  then\n    echo \"Production did not match the build number within $timeout_seconds\
        \ seconds\"\n    exit 1\n  fi\n  echo \"Production is not up to date with\
        \ the build commit\"\n  sleep 10\ndone\necho \"Production is up to date with\
        \ the build commit\"\n"
    - name: Purge Fastly edge cache per language
      env:
        LANGUAGES: ${{ inputs.languages || 'en' }}
      run: npm run purge-fastly-edge-cache-per-language
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
