name: Remove PRs from FR project v2 when FR label is removed
on:
  workflow_dispatch: {}
permissions:
  pull-requests: write
  contents: read
jobs:
  label-removed:
    name: Remove from FR v2 project
    runs-on: ubuntu-latest
    if: '(github.event.label.name == ''docs-content-fr'')

      && (github.repository == ''github/docs-internal'')

      '
    steps:
    - name: Remove issue from FR v2 project
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
        PR_NUMBER: ${{ github.event.pull_request.number || inputs.PR_NUMBER }}
        PROJECT_NUMBER: 11672
      run: "echo \"Finding item in project...\"\n\nITEM_ID=$(gh project item-list\
        \ $PROJECT_NUMBER --owner github --limit 100 --format json | jq \".items[]\
        \ | select(.content.number == $PR_NUMBER).id\")\n\nif [ -n \"$ITEM_ID\" ];\
        \ then\n  echo \"Archiving item $ITEM_ID ...\"\n  gh project item-archive\
        \ $PROJECT_NUMBER --owner github --id $ITEM_ID\nelse\n  echo \"Pull request\
        \ number $PR_NUMBER not found on FR v2 Project\"\nfi\n\necho \"done\"\n"
