name: Site policy sync
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  sync:
    name: Get the latest docs
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged
      == true && github.repository == 'github/docs-internal')
    runs-on: ubuntu-latest
    steps:
    - name: checkout docs-internal
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - name: checkout public site-policy
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        repository: github/site-policy
        token: ${{ secrets.API_TOKEN_SITEPOLICY }}
        fetch-depth: ''
        path: public-repo
    - name: Commits internal policies to copy of public repo with descriptive message
        from triggering PR title
      env:
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: 'cd public-repo

        git config --local user.name ''site-policy-bot''

        git config --local user.email ''site-policy-bot@github.com''

        rm -rf Policies

        cp -r ../content/site-policy Policies

        git status

        git checkout -b automated-sync-$GITHUB_RUN_ID

        git add .

        echo PR_TITLE: $PR_TITLE

        [[ ! -z $PR_TITLE ]] && DESCRIPTION="${PR_TITLE}" || DESCRIPTION="Update manually
        triggered by workflow"

        echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

        git commit -m "$(echo $DESCRIPTION)"

        '
    - name: If there are changes to push, create a branch in the public repo and push
        changes
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
      run: "cd public-repo\ngit config --local user.name 'site-policy-bot'\ngit config\
        \ --local user.email 'site-policy-bot@github.com'\nNUM_FILES_CHANGED=$(git\
        \ diff --name-only HEAD^..HEAD | wc -l)\nif [[ $NUM_FILES_CHANGED -ge 1 ]]\n\
        \  then\n    git push --set-upstream origin automated-sync-$GITHUB_RUN_ID\n\
        \  else\n    echo \"No updates to push to the public repo\"\nfi\n"
