name: Sync Secret Scanning data
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
  cancel-in-progress: true
jobs:
  update-secret-scanning-file:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Sync secret scanning data
      id: secret-scanning-sync
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
      run: 'npm run sync-secret-scanning

        '
    - name: Create a pull request
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_BOT_PAT_BASE }}
      run: "# If nothing to commit, exit now. It's fine.\nchanges=$(git diff --name-only\
        \ | wc -l)\nuntracked=$(git status --untracked-files --short | wc -l)\nif\
        \ [[ $changes -eq 0 ]] && [[ $untracked -eq 0 ]]; then\n  echo \"There are\
        \ no changes to commit. Exiting...\"\n  exit 0\nfi\n\ngit config --global\
        \ user.name \"docs-bot\"\ngit config --global user.email \"77750099+docs-bot@users.noreply.github.com\"\
        \n\nbranchname=sync-secret-scanning-`date +%Y%m%d%H%M%S`\n\nremotesha=$(git\
        \ ls-remote --heads origin $branchname)\nif [ -n \"$remotesha\" ]; then\n\
        \  # output is not empty, it means the remote branch exists\n  echo \"Branch\
        \ $branchname already exists in 'github/docs-internal'. Exiting...\"\n  exit\
        \ 0\nfi\n\ngit checkout -b $branchname\ngit add .\ngit commit -m \"Add updated\
        \ secret scanning data\"\ngit push origin $branchname\n\necho \"Creating pull\
        \ request...\"\ngh pr create \\\n  --title \"Sync secret scanning data\" \\\
        \n  --body '\U0001F44B humans. This PR updates the secret scanning data with\
        \ the latest changes from github/token-scanning-service.\n\n  /cc @github/docs-content-security-products\n\
        \n  If CI does not pass or other problems arise, contact #docs-engineering\
        \ on Slack.' \\\n  --repo github/docs-internal \\\n  --label secret-scanning-pipeline,'skip\
        \ FR board',ready-for-doc-review,workflow-generated \\\n  --head=$branchname\n"
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
