name: Test changed content
on:
  pull_request:
    branches:
    - main
    paths:
    - content/**
    - .github/workflows/test-changed-content.yml
permissions:
  contents: read
jobs:
  test-changed-content:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs'
      }}
    steps:
    - name: Check out repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/get-docs-early-access
      if: ${{ github.repository == 'github/docs-internal' }}
      with:
        token: ${{ secrets.DOCS_BOT_PAT_BASE }}
    - uses: ./.github/actions/cache-nextjs
    - name: Run build script
      run: npm run build
    - name: Get changed files
      id: changed_files
      uses: ./.github/actions/get-changed-files
      with:
        files: content/**
    - name: Run tests
      env:
        CHANGED_FILES: ${{ steps.changed_files.outputs.filtered_changed_files }}
        DELETED_FILES: ${{ steps.changed_files.outputs.filtered_deleted_files }}
      run: npm test -- src/content-render/tests/render-changed-and-deleted-files.js
