name: Test
on:
  workflow_dispatch: null
  merge_group: null
  pull_request: null
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref
    || github.ref }}
  cancel-in-progress: true
env:
  ELASTICSEARCH_URL: http://localhost:9200/
jobs:
  test:
    name: ${{ matrix.name }}
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        name:
        - archives
        - article-api
        - assets
        - audit-logs
        - automated-pipelines
        - changelogs
        - color-schemes
        - content-linter
        - content-render
        - data-directory
        - early-access
        - events
        - fixtures
        - frame
        - ghes-releases
        - github-apps
        - graphql
        - landings
        - languages
        - learning-track
        - observability
        - products
        - redirects
        - release-notes
        - rest
        - search
        - secret-scanning
        - shielding
        - tracking
        - versions
        - webhooks
        - workflows
        isPrivateRepo:
        - ${{ github.repository == 'github/docs-internal' }}
        exclude:
        - name: languages
          isPrivateRepo: false
    steps:
    - name: Check out repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: ./.github/actions/setup-elasticsearch
      if: ${{ matrix.name == 'search' || matrix.name == 'languages' }}
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/get-docs-early-access
      if: ${{ github.repository == 'github/docs-internal' }}
      with:
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
    - name: Check the test fixture data (if applicable)
      if: ${{ matrix.name == 'fixtures' }}
      run: npm run copy-fixture-data -- --check
    - name: Check the test fixture content (if applicable)
      if: ${{ matrix.name == 'fixtures' }}
      env:
        ROOT: src/fixtures/fixtures
      run: "# If either of these fail, it means our fixture content's internal\n#\
        \ links can and should be updated.\nnpm run update-internal-links -- --dry-run\
        \ --check --strict \\\n  src/fixtures/fixtures/content \\\n  --exclude src/fixtures/fixtures/content/get-started/foo/typo-autotitling.md\
        \ \\\n  --exclude src/fixtures/fixtures/content/get-started/foo/anchor-autotitling.md\n\
        npm run update-internal-links -- --dry-run --check --strict \\\n  src/fixtures/fixtures/data\n"
    - name: Clone all translations
      if: ${{ matrix.name == 'languages' }}
      uses: ./.github/actions/clone-translations
      with:
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
    - name: Gather files changed
      if: ${{ matrix.name == 'content-linter' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.number }}
        HEAD: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref
          }}
      run: "# Find the file diff in the pull request or merge group\n# If its a pull\
        \ request, use the faster call to the GitHub API\n# For push, workflow_dispatch,\
        \ and merge_group, use git diff\nif [ -n \"$PR\" ]\nthen\n  echo __ running\
        \ gh pr diff __\n  DIFF=`gh pr diff $PR --name-only`\nelif [ -n \"$HEAD\"\
        \ ]\nthen\n  echo __ running git fetch main __\n  git fetch origin main --depth\
        \ 1\n  echo __ running git diff __\n  DIFF=`git diff --name-only origin/main`\n\
        else\n  echo __ no head, empty diff __\n  DIFF=''\nfi\n# So we can inspect\
        \ the output\necho __ DIFF found __\necho $DIFF\n\n# So that becomes a string\
        \ like `foo.js path/bar.md`\n# Must do this because the list of files can\
        \ be HUGE. Especially\n# in a repo-sync when there are lots of translation\
        \ files involved.\necho __ format, write to get_diff_files.txt __\necho $DIFF\
        \ | tr '\\n' ' ' > get_diff_files.txt\n"
    - uses: ./.github/actions/cache-nextjs
    - name: Run build script
      run: npm run build
    - uses: ./.github/actions/warmup-remotejson-cache
      if: ${{ matrix.name == 'redirects' }}
    - uses: ./.github/actions/precompute-pageinfo
      if: ${{ matrix.name == 'article-api' }}
      env:
        ROOT: src/fixtures/fixtures
    - name: Index fixtures into the local Elasticsearch
      if: ${{ matrix.name == 'search' || matrix.name == 'languages' }}
      run: npm run index-test-fixtures
    - name: Run tests
      env:
        DIFF_FILE: get_diff_files.txt
        CHANGELOG_CACHE_FILE_PATH: src/fixtures/fixtures/changelog-feed.json
        ENABLED_LANGUAGES: ${{ matrix.name == 'languages' && 'all' || '' }}
        ROOT: ${{ (matrix.name == 'fixtures' || matrix.name == 'article-api' || matrix.name
          == 'landings' ) && 'src/fixtures/fixtures' || '' }}
        TRANSLATIONS_FIXTURE_ROOT: ${{ (matrix.name == 'fixtures' || matrix.name ==
          'article-api') && 'src/fixtures/fixtures/translations' || '' }}
      run: npm test -- src/${{ matrix.name }}/tests/
