name: Test changed content
on:
  pull_request:
    branches:
    - main
    paths:
    - content/**
    - .github/workflows/test-changed-content.yml
permissions:
  contents: read
jobs:
  test-changed-content:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs'
      }}
    steps:
    - name: Check out repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 2
    - uses: ./.github/actions/node-npm-setup
    - uses: ./.github/actions/get-docs-early-access
      if: ${{ github.repository == 'github/docs-internal' }}
      with:
        token: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
    - uses: ./.github/actions/cache-nextjs
    - name: Run build script
      run: npm run build
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32
      with:
        safe_output: false
        files: content/**
        output_renamed_files_as_deleted_and_added: true
    - name: Run tests
      env:
        CHANGED_FILES: ${{ steps.changed-files.outputs.modified_files }}
        DELETED_FILES: ${{ steps.changed-files.outputs.deleted_files }}
      run: npm test -- src/content-render/tests/render-changed-and-deleted-files.js
