name: Triage new issue comments
on:
  workflow_dispatch: {}
permissions:
  contents: read
  issues: write
jobs:
  triage-issue-comments:
    if: ${{ github.repository == 'github/docs' && !github.event.issue.pull_request
      }}
    runs-on: ubuntu-latest
    steps:
    - name: Check if the event originated from a team member
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      id: is-internal-contributor
      with:
        result-encoding: string
        script: "const repo = context.payload.repository.name\nconst org = context.payload.repository.owner.login\n\
          const actor = context.actor\nlet collaboratorStatus = ''\ntry {\n  collaboratorStatus\
          \ = await github.request('GET /repos/{owner}/{repo}/collaborators/{username}',\
          \ {\n    owner: org,\n    repo: repo,\n    username: actor\n  })\n  console.log(`This\
          \ issue was commented on by a Hubber.`)\n  return 'true'\n} catch (error)\
          \ {\n  console.log(`This issue was commented on by an external contributor.`)\n\
          \  return 'false'\n}\n"
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Check issue exists
      id: exists
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
      run: "if gh issue view $ISSUE_URL > /dev/null 2>&1\nthen\n  echo \"exists=y\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"exists=n\" >> $GITHUB_OUTPUT\nfi\n"
    - name: Label issues with new comments with 'triage'
      uses: ./.github/actions/labeler
      if: ${{ steps.is-internal-contributor.outputs.result == 'false' && steps.exists.outputs.exists
        == 'y' }}
      with:
        addLabels: triage
        ignoreIfLabeled: true
    - uses: ./.github/actions/slack-alert
      if: ${{ failure() }}
      with:
        slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
        slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
