name: Validate asset images
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  validate-asset-images:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs'
      }}
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
    - uses: ./.github/actions/node-npm-setup
    - name: Validate all asset images
      run: npm run validate-asset-images
